"""init migration

Revision ID: 2110cc75d5f3
Revises: 
Create Date: 2023-05-24 16:00:36.116648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2110cc75d5f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SEA_divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SEA_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('patronymic', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SEA_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SEA_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staffer_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('date_of_employment', sa.Date(), nullable=False),
    sa.Column('date_of_dismissal', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['SEA_divisions.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['SEA_positions.id'], ),
    sa.ForeignKeyConstraint(['staffer_id'], ['SEA_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SEA_job')
    op.drop_table('SEA_positions')
    op.drop_table('SEA_employees')
    op.drop_table('SEA_divisions')
    # ### end Alembic commands ###
